name: flight_tracker

description: A Flutter app for tracking flights using AviationStack API and Google Maps.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.4.5

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/plane.png
